/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.VentaControlador;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Venta;

/**
 *
 * @author Carlos Duran, Ivan David Bejarano Diaz, Zuri Saday Messu, Michael Steven Reyes
 */
public class FrmConsultarVenta extends javax.swing.JFrame {

    private DefaultTableModel modeloTabla;

    /**
     * Creates new form FrmConsultarPaquete
     */
    public FrmConsultarVenta() {
        initComponents();
        modeloTabla = (DefaultTableModel) tablaVenta.getModel();
        cargarTabla();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVenta = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnCancelarVenta = new javax.swing.JButton();
        btnVerDetalle = new javax.swing.JButton();
        cbEstado = new javax.swing.JComboBox<>();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtNumeroVenta = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel47.setBackground(new java.awt.Color(204, 204, 204));
        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel47.setText("LISTADO DE VENTAS");

        tablaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código Venta", "Cliente", "Paquete", "Origen", "Destino", "Tarifa/Día", "Cantidad", "Días permanencia", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaVenta);

        btnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNuevo.setText("REGISTRAR NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevojButtonGuardarVentaActionPerformed(evt);
            }
        });

        btnCancelarVenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelarVenta.setText("CANCELAR VENTA");
        btnCancelarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarVentajButtonGuardarVentaActionPerformed(evt);
            }
        });

        btnVerDetalle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVerDetalle.setText("VER DETALLE");
        btnVerDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetallejButtonGuardarVentaActionPerformed(evt);
            }
        });

        cbEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "CANCELADO" }));
        cbEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbEstadojComboBoxTipoIDMouseClicked(evt);
            }
        });
        cbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadojComboBoxTipoIDActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel41.setText("Estado");

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel42.setText("Número de venta");

        txtNumeroVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroVentajTextFieldNumeroIDActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarjButtonGuardarVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnNuevo)
                                .addGap(18, 18, 18)
                                .addComponent(btnVerDetalle)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelarVenta))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel41)
                                .addGap(18, 18, 18)
                                .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel42)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNumeroVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel47)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42)
                    .addComponent(txtNumeroVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnCancelarVenta)
                    .addComponent(btnVerDetalle))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevojButtonGuardarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevojButtonGuardarVentaActionPerformed
        FrmRegistrarVenta frmRegistrar = new FrmRegistrarVenta();
        frmRegistrar.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                cargarTabla();
            }
        });
        frmRegistrar.setVisible(true);
    }//GEN-LAST:event_btnNuevojButtonGuardarVentaActionPerformed

    private void btnCancelarVentajButtonGuardarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarVentajButtonGuardarVentaActionPerformed
        cancelarVentaSeleccionada();
    }//GEN-LAST:event_btnCancelarVentajButtonGuardarVentaActionPerformed

    private void btnVerDetallejButtonGuardarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetallejButtonGuardarVentaActionPerformed
        verDetalleVenta();
    }//GEN-LAST:event_btnVerDetallejButtonGuardarVentaActionPerformed

    private void cbEstadojComboBoxTipoIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbEstadojComboBoxTipoIDMouseClicked

    }//GEN-LAST:event_cbEstadojComboBoxTipoIDMouseClicked

    private void cbEstadojComboBoxTipoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstadojComboBoxTipoIDActionPerformed

    }//GEN-LAST:event_cbEstadojComboBoxTipoIDActionPerformed

    private void txtNumeroVentajTextFieldNumeroIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroVentajTextFieldNumeroIDActionPerformed

    }//GEN-LAST:event_txtNumeroVentajTextFieldNumeroIDActionPerformed

    private void btnBuscarjButtonGuardarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarjButtonGuardarVentaActionPerformed
        cargarTabla();
    }//GEN-LAST:event_btnBuscarjButtonGuardarVentaActionPerformed

    private void cargarTabla() {
        modeloTabla.setRowCount(0);
        try {
            boolean activo = cbEstado.getSelectedItem().toString().equals("ACTIVO");
            String codigoVenta = txtNumeroVenta.getText().trim();
            ArrayList<Venta> lista = VentaControlador.buscarPorFiltro(activo, codigoVenta);

            for (Venta venta : lista) {
                modeloTabla.addRow(new Object[]{
                    venta.getCodigoVenta(),
                    venta.getNombreCliente(),
                    venta.getNombrePaquete(),
                    venta.getOrigen(),
                    venta.getDestino(),
                    venta.getTarifaDia(),
                    venta.getUnidades(),
                    venta.getDiasPermanencia(),
                    String.format("%.2f", venta.getTotal())
                });
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar las ventas: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cancelarVentaSeleccionada() {
        int fila = tablaVenta.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione una venta de la tabla.",
                    "Validacion",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String codigoVenta = modeloTabla.getValueAt(fila, 0).toString();
        int confirmacion = JOptionPane.showConfirmDialog(this,
                "Desea cancelar la venta " + codigoVenta + "?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION);

        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }

        String error = VentaControlador.cancelarVenta(codigoVenta);
        if (error != null) {
            JOptionPane.showMessageDialog(this,
                    error,
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        JOptionPane.showMessageDialog(this,
                "Venta cancelada correctamente.",
                "Informacion",
                JOptionPane.INFORMATION_MESSAGE);
        cargarTabla();
    }

    private void verDetalleVenta() {
        int fila = tablaVenta.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione una venta de la tabla.",
                    "Validacion",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String codigoVenta = modeloTabla.getValueAt(fila, 0).toString();
        try {
            Venta venta = VentaControlador.buscarPorCodigo(codigoVenta);
            if (venta == null) {
                JOptionPane.showMessageDialog(this,
                        "No se encontro la venta.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            FrmVerDetalleVenta frmDetalle = new FrmVerDetalleVenta(venta);
            frmDetalle.setVisible(true);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,
                    "Error al consultar la venta: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConsultarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConsultarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConsultarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConsultarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConsultarVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelarVenta;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnVerDetalle;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaVenta;
    private javax.swing.JTextField txtNumeroVenta;
    // End of variables declaration//GEN-END:variables
}
