/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.PaqueteControlador;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos Duran, Ivan David Bejarano Diaz, Zuri Saday Messu, Michael Steven Reyes
 */
public class FrmPrincipal extends javax.swing.JFrame {

    FrmConsultarPaquete frmConsultarPaquete;
    FrmRegistrarPaquete frmRegistrarPaquete;
    FrmConsultarVenta frmConsultarVenta;
    FrmRegistrarVenta frmRegistrarVenta;
    FrmVerDetalleVenta frmVerDetalleVenta;
    
    
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbLogged = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mPaquetes = new javax.swing.JMenu();
        menuRegistrarPaquete = new javax.swing.JMenuItem();
        menuConsultarPaquete = new javax.swing.JMenuItem();
        mVentas = new javax.swing.JMenu();
        menuRegistrarVenta = new javax.swing.JMenuItem();
        MenuConsultarVenta = new javax.swing.JMenuItem();
        mArchivoObjetos = new javax.swing.JMenu();
        menuCargarDatos = new javax.swing.JMenuItem();
        menuGuardarDatos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbLogged.setBackground(new java.awt.Color(0, 102, 102));
        lbLogged.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbLogged.setForeground(new java.awt.Color(255, 255, 255));
        lbLogged.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogged.setOpaque(true);

        mPaquetes.setText("Paquetes");
        mPaquetes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        menuRegistrarPaquete.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuRegistrarPaquete.setText("Registrar paquete");
        menuRegistrarPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarPaqueteActionPerformed(evt);
            }
        });
        mPaquetes.add(menuRegistrarPaquete);

        menuConsultarPaquete.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuConsultarPaquete.setText("Consultar paquete");
        menuConsultarPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarPaqueteActionPerformed(evt);
            }
        });
        mPaquetes.add(menuConsultarPaquete);

        jMenuBar1.add(mPaquetes);

        mVentas.setText("Ventas");
        mVentas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        mVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mVentasMouseClicked(evt);
            }
        });

        menuRegistrarVenta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuRegistrarVenta.setText("Registrar venta");
        menuRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarVentaActionPerformed(evt);
            }
        });
        mVentas.add(menuRegistrarVenta);

        MenuConsultarVenta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        MenuConsultarVenta.setText("Consultar venta");
        MenuConsultarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConsultarVentaActionPerformed(evt);
            }
        });
        mVentas.add(MenuConsultarVenta);

        jMenuBar1.add(mVentas);

        mArchivoObjetos.setText("Archivo de objetos");
        mArchivoObjetos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        mArchivoObjetos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mArchivoObjetosMouseClicked(evt);
            }
        });

        menuCargarDatos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuCargarDatos.setText("Cargar datos");
        menuCargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCargarDatosActionPerformed(evt);
            }
        });
        mArchivoObjetos.add(menuCargarDatos);

        menuGuardarDatos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuGuardarDatos.setText("Guardar datos");
        menuGuardarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGuardarDatosActionPerformed(evt);
            }
        });
        mArchivoObjetos.add(menuGuardarDatos);

        jMenuBar1.add(mArchivoObjetos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbLogged, javax.swing.GroupLayout.DEFAULT_SIZE, 1003, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbLogged, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuRegistrarPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarPaqueteActionPerformed
        // TODO add your handling code here:
        this.frmRegistrarPaquete = new FrmRegistrarPaquete();
        frmRegistrarPaquete.setVisible(true);
    }//GEN-LAST:event_menuRegistrarPaqueteActionPerformed

    private void mVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mVentasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mVentasMouseClicked

    private void mArchivoObjetosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mArchivoObjetosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mArchivoObjetosMouseClicked

    private void menuConsultarPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarPaqueteActionPerformed
        // TODO add your handling code here:
        this.frmConsultarPaquete = new FrmConsultarPaquete();
        frmConsultarPaquete.setVisible(true);
    }//GEN-LAST:event_menuConsultarPaqueteActionPerformed

    private void menuRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarVentaActionPerformed
        // TODO add your handling code here:
        this.frmRegistrarVenta = new FrmRegistrarVenta();
        frmRegistrarVenta.setVisible(true);
    }//GEN-LAST:event_menuRegistrarVentaActionPerformed

    private void MenuConsultarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConsultarVentaActionPerformed
        // TODO add your handling code here:
        this.frmConsultarVenta = new FrmConsultarVenta();
        frmConsultarVenta.setVisible(true);
    }//GEN-LAST:event_MenuConsultarVentaActionPerformed

    private void menuCargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCargarDatosActionPerformed
        try {
            PaqueteControlador.cargarDesdeArchivo();
            JOptionPane.showMessageDialog(this,
                    "Datos cargados correctamente.",
                    "Informacion",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar datos: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuCargarDatosActionPerformed

    private void menuGuardarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGuardarDatosActionPerformed
        try {
            PaqueteControlador.guardarEnArchivo();
            JOptionPane.showMessageDialog(this,
                    "Datos guardados correctamente.",
                    "Informacion",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,
                    "Error al guardar datos: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuGuardarDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuConsultarVenta;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbLogged;
    private javax.swing.JMenu mArchivoObjetos;
    private javax.swing.JMenu mPaquetes;
    private javax.swing.JMenu mVentas;
    private javax.swing.JMenuItem menuCargarDatos;
    private javax.swing.JMenuItem menuConsultarPaquete;
    private javax.swing.JMenuItem menuGuardarDatos;
    private javax.swing.JMenuItem menuRegistrarPaquete;
    private javax.swing.JMenuItem menuRegistrarVenta;
    // End of variables declaration//GEN-END:variables
}
