/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author elden
 */
public class FrmRegistrarPaquete extends javax.swing.JFrame {

    /**
     * Creates new form FrmCrearPaquete
     */
    public FrmRegistrarPaquete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        REGISTRODEVENTA2 = new javax.swing.JPanel();
        txtCodigoPaquete = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        cbCategoria = new javax.swing.JComboBox<>();
        jLabel50 = new javax.swing.JLabel();
        txtNombrePaquete = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        txtTarifaDia = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        chHotel = new javax.swing.JCheckBox();
        chVuelo = new javax.swing.JCheckBox();
        chSoloDesayuno = new javax.swing.JCheckBox();
        chAsistenciaMedica = new javax.swing.JCheckBox();
        chAlimentación = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTipologia = new javax.swing.JTextField();
        cbOrigen = new javax.swing.JComboBox<>();
        cbDestino = new javax.swing.JComboBox<>();
        btnAgregarDestino = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDestinosSeleccionados = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        REGISTRODEVENTA2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        REGISTRODEVENTA2.setPreferredSize(new java.awt.Dimension(940, 290));

        jLabel47.setBackground(new java.awt.Color(204, 204, 204));
        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel47.setText("PAQUETE TURISTICO");

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel48.setText("Codigo Paquete");

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel49.setText("Categoria");

        cbCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Único", "Múltiple" }));
        cbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriajComboBoxCategoriaActionPerformed(evt);
            }
        });

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel50.setText("Nombre Paquete");

        txtNombrePaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePaquetejTextFieldNombrePaqueteActionPerformed(evt);
            }
        });

        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel51.setText("Origen");

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel52.setText("Tarifa/ día");

        jLabel53.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel53.setText("Destino ");

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarjButtonGuardarVentaActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarjButtonLimpiarActionPerformed(evt);
            }
        });

        chHotel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chHotel.setSelected(true);
        chHotel.setText("Hotel");
        chHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chHotelActionPerformed(evt);
            }
        });

        chVuelo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chVuelo.setSelected(true);
        chVuelo.setText("Vuelo");

        chSoloDesayuno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chSoloDesayuno.setText("Solo Desayuno");

        chAsistenciaMedica.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chAsistenciaMedica.setSelected(true);
        chAsistenciaMedica.setText("Asistencia Medica");

        chAlimentación.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chAlimentación.setText("Alimentación ");
        chAlimentación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chAlimentaciónActionPerformed(evt);
            }
        });

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("DESCRIPCIÓN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tipología");

        cbOrigen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ARMENIA", "BARRANQUILLA", "BOGOTA", "BOGOTA D.C.", "BUCARAMANGA", "CALI", "CARTAGENA", "CUCUTA", "IBAGUE", "MANIZALES", "MEDELLIN", "MONTERIA", "NEIVA", "PASTO", "PEREIRA", "POPAYAN", "SAN ANDRES", "SANTA MARTA", "TUNJA", "VALLEDUPAR", "VILLAVICENCIO" }));
        cbOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOrigenjComboBoxCategoriaActionPerformed(evt);
            }
        });

        cbDestino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ARMENIA", "BARRANQUILLA", "BOGOTA", "BOGOTA D.C.", "BUCARAMANGA", "CALI", "CARTAGENA", "CUCUTA", "IBAGUE", "MANIZALES", "MEDELLIN", "MONTERIA", "NEIVA", "PASTO", "PEREIRA", "POPAYAN", "SAN ANDRES", "SANTA MARTA", "TUNJA", "VALLEDUPAR", "VILLAVICENCIO" }));
        cbDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDestinojComboBoxCategoriaActionPerformed(evt);
            }
        });

        btnAgregarDestino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregarDestino.setText("Agregar");
        btnAgregarDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDestinojButtonGuardarVentaActionPerformed(evt);
            }
        });

        txtDestinosSeleccionados.setEditable(false);
        txtDestinosSeleccionados.setColumns(20);
        txtDestinosSeleccionados.setRows(1);
        jScrollPane2.setViewportView(txtDestinosSeleccionados);

        javax.swing.GroupLayout REGISTRODEVENTA2Layout = new javax.swing.GroupLayout(REGISTRODEVENTA2);
        REGISTRODEVENTA2.setLayout(REGISTRODEVENTA2Layout);
        REGISTRODEVENTA2Layout.setHorizontalGroup(
            REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                        .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel50)
                            .addComponent(jLabel2)
                            .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel53))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, REGISTRODEVENTA2Layout.createSequentialGroup()
                                .addComponent(txtTipologia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTarifaDia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, REGISTRODEVENTA2Layout.createSequentialGroup()
                                        .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(160, 160, 160))))
                            .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                                    .addComponent(chVuelo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(chHotel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(chAsistenciaMedica)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(chAlimentación)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(chSoloDesayuno))
                                .addComponent(cbOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombrePaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                                    .addComponent(cbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnAgregarDestino))
                                .addComponent(jScrollPane2))))
                    .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                        .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCodigoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel49)
                                .addGap(18, 18, 18)
                                .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel47))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(90, 90, 90)
                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                        .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18))
                    .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        REGISTRODEVENTA2Layout.setVerticalGroup(
            REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                        .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel48)
                            .addComponent(jLabel49)
                            .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel50)
                            .addComponent(txtNombrePaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTarifaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel52)
                            .addComponent(txtTipologia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel51)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel53)
                    .addComponent(btnAgregarDestino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chVuelo)
                    .addComponent(chHotel)
                    .addComponent(chAsistenciaMedica)
                    .addComponent(chAlimentación)
                    .addComponent(chSoloDesayuno))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(REGISTRODEVENTA2, javax.swing.GroupLayout.DEFAULT_SIZE, 1004, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(REGISTRODEVENTA2, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbCategoriajComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriajComboBoxCategoriaActionPerformed

    }//GEN-LAST:event_cbCategoriajComboBoxCategoriaActionPerformed

    private void txtNombrePaquetejTextFieldNombrePaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePaquetejTextFieldNombrePaqueteActionPerformed

    }//GEN-LAST:event_txtNombrePaquetejTextFieldNombrePaqueteActionPerformed

    private void btnLimpiarjButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarjButtonLimpiarActionPerformed
        

    }//GEN-LAST:event_btnLimpiarjButtonLimpiarActionPerformed

    private void chHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chHotelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chHotelActionPerformed

    private void chAlimentaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chAlimentaciónActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chAlimentaciónActionPerformed

    private void btnGuardarjButtonGuardarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarjButtonGuardarVentaActionPerformed
        
    }//GEN-LAST:event_btnGuardarjButtonGuardarVentaActionPerformed

    private void cbOrigenjComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOrigenjComboBoxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbOrigenjComboBoxCategoriaActionPerformed

    private void cbDestinojComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDestinojComboBoxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDestinojComboBoxCategoriaActionPerformed

    private void btnAgregarDestinojButtonGuardarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDestinojButtonGuardarVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarDestinojButtonGuardarVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistrarPaquete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel REGISTRODEVENTA2;
    private javax.swing.JButton btnAgregarDestino;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JComboBox<String> cbDestino;
    private javax.swing.JComboBox<String> cbOrigen;
    private javax.swing.JCheckBox chAlimentación;
    private javax.swing.JCheckBox chAsistenciaMedica;
    private javax.swing.JCheckBox chHotel;
    private javax.swing.JCheckBox chSoloDesayuno;
    private javax.swing.JCheckBox chVuelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtCodigoPaquete;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextArea txtDestinosSeleccionados;
    private javax.swing.JTextField txtNombrePaquete;
    private javax.swing.JTextField txtTarifaDia;
    private javax.swing.JTextField txtTipologia;
    // End of variables declaration//GEN-END:variables
}
