/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author elden
 */
public class FrmRegistrarVenta extends javax.swing.JFrame {

    /**
     * Creates new form FrmRegistrarVenta
     */
    public FrmRegistrarVenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        REGISTRODEVENTA2 = new javax.swing.JPanel();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        cbTipoId = new javax.swing.JComboBox<>();
        jLabel42 = new javax.swing.JLabel();
        txtNumeroId = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        txtNombreContacto = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        txtPorcentajeDescuento = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        cbEmpresa = new javax.swing.JComboBox<>();
        txtCodigoPaquete = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        txtNombrePaquete = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        txtTarifaDia = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        txtDiasPermanencia = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        txtUnidades = new javax.swing.JTextField();
        btnGuardarVenta = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        chHotel = new javax.swing.JCheckBox();
        chVuelo = new javax.swing.JCheckBox();
        chSoloDesayuno = new javax.swing.JCheckBox();
        chAsistenciaMedica = new javax.swing.JCheckBox();
        chAlimentación = new javax.swing.JCheckBox();
        txtOrigen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTipología = new javax.swing.JTextField();
        btnBuscarPaquete = new javax.swing.JButton();
        txtCategoria = new javax.swing.JTextField();
        txtDestino = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnBuscarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        REGISTRODEVENTA2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClientejTextFieldNombreClienteActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setText("Nombre Cliente");

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel39.setText("REGISTRO DE VENTA");

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel40.setText("Email");

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel41.setText("Tipo ID");

        cbTipoId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbTipoId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C - Cédula", "N - NIT" }));
        cbTipoId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbTipoIdjComboBoxTipoIDMouseClicked(evt);
            }
        });
        cbTipoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoIdjComboBoxTipoIDActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel42.setText("Núm.ID");

        txtNumeroId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroIdjTextFieldNumeroIDActionPerformed(evt);
            }
        });

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonomailActionPerformed(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel43.setText("Teléfono");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailjTextFieldTelefonoActionPerformed(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel44.setText("Nombre Contacto");

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel45.setText("Descuento %");

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel46.setText("Empresa?");

        cbEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbEmpresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "SI" }));

        jLabel47.setBackground(new java.awt.Color(204, 204, 204));
        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel47.setText("PAQUETE TURISTICO");

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel48.setText("Codigo Paquete");

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel49.setText("Categoria");

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel50.setText("Nombre Paquete");

        txtNombrePaquete.setEditable(false);
        txtNombrePaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePaquetejTextFieldNombrePaqueteActionPerformed(evt);
            }
        });

        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel51.setText("Origen");

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel52.setText("Tarifa/ día");

        txtTarifaDia.setEditable(false);

        jLabel53.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel53.setText("Destino ");

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel54.setText("Días Permanencia");

        txtDiasPermanencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiasPermanenciaActionPerformed(evt);
            }
        });

        jLabel55.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel55.setText("Unidades");

        txtUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnidadesjTextFieldUnidadesActionPerformed(evt);
            }
        });

        btnGuardarVenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardarVenta.setText("GUARDAR VENTA");
        btnGuardarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarVentajButtonGuardarVentaActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarjButtonLimpiarActionPerformed(evt);
            }
        });

        chHotel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chHotel.setText("Hotel");
        chHotel.setEnabled(false);
        chHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chHotelActionPerformed(evt);
            }
        });

        chVuelo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chVuelo.setText("Vuelo");
        chVuelo.setEnabled(false);

        chSoloDesayuno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chSoloDesayuno.setText("Solo Desayuno");
        chSoloDesayuno.setEnabled(false);

        chAsistenciaMedica.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chAsistenciaMedica.setText("Asistencia Medica");
        chAsistenciaMedica.setEnabled(false);

        chAlimentación.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chAlimentación.setText("Alimentación ");
        chAlimentación.setEnabled(false);
        chAlimentación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chAlimentaciónActionPerformed(evt);
            }
        });

        txtOrigen.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tipología");

        txtTipología.setEditable(false);

        btnBuscarPaquete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarPaquete.setText("Buscar");
        btnBuscarPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPaquetejButtonLimpiarActionPerformed(evt);
            }
        });

        txtCategoria.setEditable(false);

        txtDestino.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("DESCRIPCIÓN");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        btnBuscarCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClientejButtonLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout REGISTRODEVENTA2Layout = new javax.swing.GroupLayout(REGISTRODEVENTA2);
        REGISTRODEVENTA2.setLayout(REGISTRODEVENTA2Layout);
        REGISTRODEVENTA2Layout.setHorizontalGroup(
            REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                        .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel39)
                            .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel41)))
                                .addGap(18, 18, 18)
                                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                                        .addComponent(cbTipoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel42)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNumeroId)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBuscarCliente))
                                    .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel43)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel45)
                                    .addComponent(jLabel44))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                                        .addComponent(txtPorcentajeDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel46)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbEmpresa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtNombreContacto))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                        .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel50)
                                    .addComponent(jLabel49)
                                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel53))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                                        .addComponent(txtTarifaDia, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel54)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDiasPermanencia, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, REGISTRODEVENTA2Layout.createSequentialGroup()
                                            .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtTipología))
                                        .addComponent(txtDestino)
                                        .addComponent(txtOrigen, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNombrePaquete, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, REGISTRODEVENTA2Layout.createSequentialGroup()
                                            .addComponent(chVuelo)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(chHotel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(chAsistenciaMedica)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(chAlimentación)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(chSoloDesayuno)))))
                            .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCodigoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarPaquete))
                            .addComponent(jLabel47))
                        .addGap(16, 16, 16)
                        .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                            .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnGuardarVenta)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar))))
                    .addComponent(jSeparator4))
                .addContainerGap())
        );
        REGISTRODEVENTA2Layout.setVerticalGroup(
            REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel39)
                .addGap(18, 18, 18)
                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(cbTipoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42)
                    .addComponent(txtNumeroId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44)
                    .addComponent(txtNombreContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(jLabel45)
                    .addComponent(txtPorcentajeDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(REGISTRODEVENTA2Layout.createSequentialGroup()
                        .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel48)
                            .addComponent(btnBuscarPaquete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel50)
                            .addComponent(txtNombrePaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel49)
                            .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txtTipología, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel51))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel53)
                            .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chVuelo)
                            .addComponent(chHotel)
                            .addComponent(chAsistenciaMedica)
                            .addComponent(chAlimentación)
                            .addComponent(chSoloDesayuno))
                        .addGap(18, 18, 18)
                        .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel52)
                            .addComponent(txtTarifaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel54)
                            .addComponent(txtDiasPermanencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel55)
                            .addComponent(txtUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(REGISTRODEVENTA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarVenta)
                    .addComponent(btnLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(REGISTRODEVENTA2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(REGISTRODEVENTA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreClientejTextFieldNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClientejTextFieldNombreClienteActionPerformed

    }//GEN-LAST:event_txtNombreClientejTextFieldNombreClienteActionPerformed

    private void cbTipoIdjComboBoxTipoIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbTipoIdjComboBoxTipoIDMouseClicked

    }//GEN-LAST:event_cbTipoIdjComboBoxTipoIDMouseClicked

    private void cbTipoIdjComboBoxTipoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoIdjComboBoxTipoIDActionPerformed

    }//GEN-LAST:event_cbTipoIdjComboBoxTipoIDActionPerformed

    private void txtNumeroIdjTextFieldNumeroIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroIdjTextFieldNumeroIDActionPerformed

    }//GEN-LAST:event_txtNumeroIdjTextFieldNumeroIDActionPerformed

    private void txtTelefonomailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonomailActionPerformed

    }//GEN-LAST:event_txtTelefonomailActionPerformed

    private void txtEmailjTextFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailjTextFieldTelefonoActionPerformed

    }//GEN-LAST:event_txtEmailjTextFieldTelefonoActionPerformed

    private void txtNombrePaquetejTextFieldNombrePaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePaquetejTextFieldNombrePaqueteActionPerformed

    }//GEN-LAST:event_txtNombrePaquetejTextFieldNombrePaqueteActionPerformed

    private void txtDiasPermanenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiasPermanenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiasPermanenciaActionPerformed

    private void txtUnidadesjTextFieldUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidadesjTextFieldUnidadesActionPerformed

    }//GEN-LAST:event_txtUnidadesjTextFieldUnidadesActionPerformed

    private void btnGuardarVentajButtonGuardarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarVentajButtonGuardarVentaActionPerformed
        
    }//GEN-LAST:event_btnGuardarVentajButtonGuardarVentaActionPerformed

    private void btnLimpiarjButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarjButtonLimpiarActionPerformed
    

    }//GEN-LAST:event_btnLimpiarjButtonLimpiarActionPerformed

    private void chHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chHotelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chHotelActionPerformed

    private void chAlimentaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chAlimentaciónActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chAlimentaciónActionPerformed

    private void btnBuscarPaquetejButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPaquetejButtonLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarPaquetejButtonLimpiarActionPerformed

    private void btnBuscarClientejButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClientejButtonLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarClientejButtonLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistrarVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel REGISTRODEVENTA2;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarPaquete;
    private javax.swing.JButton btnGuardarVenta;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbEmpresa;
    private javax.swing.JComboBox<String> cbTipoId;
    private javax.swing.JCheckBox chAlimentación;
    private javax.swing.JCheckBox chAsistenciaMedica;
    private javax.swing.JCheckBox chHotel;
    private javax.swing.JCheckBox chSoloDesayuno;
    private javax.swing.JCheckBox chVuelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCodigoPaquete;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtDiasPermanencia;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreContacto;
    private javax.swing.JTextField txtNombrePaquete;
    private javax.swing.JTextField txtNumeroId;
    private javax.swing.JTextField txtOrigen;
    private javax.swing.JTextField txtPorcentajeDescuento;
    private javax.swing.JTextField txtTarifaDia;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTipología;
    private javax.swing.JTextField txtUnidades;
    // End of variables declaration//GEN-END:variables
}
